spring:
  jackson:
    default-property-inclusion: always
  boot:
    admin:
      client:
        url: http://localhost:8090
#  zipkin:
#    baseUrl: http://localhost:9411
#  sleuth:
#    sampler:
#      probability: 1
  sleuth:
    otel:
      config:
        trace-id-ratio-based: 1.0
      exporter:
        otlp:
          endpoint: http://localhost:4317
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/
management:
  endpoints:
    web:
      exposure:
        include: '*'
