server:
  port: 10000
spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:file:./data/payments.db
    username: admin
    password: admin
logging:
  level:
    #org.springframework.web.client.RestTemplate: DEBUG
    pl.training: DEBUG
feign:
  client:
    config:
      products:
        logger-level: BASIC
