server:
  port: 10000
spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
logging:
  level:
    #org.springframework.web.client.RestTemplate: DEBUG
    pl.training: DEBUG
feign:
  client:
    config:
      default:
        logger-level: HEADERS
  origin: http://localhost:4200
  headers: "*"
  methods: "*"
apiPath: /orders/**
