POST http://localhost:10000/api/payments
Accept: application/json
Content-Type: application/json

{
  "requestId": 1,
  "value": "200 PLN"
}

###

GET http://localhost:10000/api/payments/2f318b81-0a60-4256-bdfb-21ce7694a804
Accept: application/json
Content-Type: application/json

###

GET http://localhost:10000/api/payments/confirmed?pageSize=2&pageNumber=0
Accept: application/json
Content-Type: application/json

###

POST http://localhost:10000/api/orders
Accept: application/json
Content-Type: application/json

{
  "orderId": 1,
  "entries": [
    {
      "productId": 1,
      "price": 100,
      "quantity": 4
    }
  ]
}

###
// RestPlaceOrderUseCaseAdapter (uses RestOrderUseCaseMapper)
// PlaceOrderUseCase
// PlaceOrderService (uses PaymentsService->PaymentServiceAdapter)
// ProcessPaymentUseCase
// ProcessPaymentUseCaseAdapter (uses PaymentDomainMapper)
// ProcessPaymentService (uses PaymentIdGenerator, PaymentFeeCalculator)
// PaymentDomainWriter
// PaymentWriterAdapter (uses PaymentDomainMapper)
// PaymentWriter
// JpaPaymentRepositoryAdapter (uses JpaPaymentRepositoryMapper)
// JpaPaymentRepository

###

GET http://localhost:8888/shop-service/development/003-Base-components

###

GET http://localhost:8888/003-Base-components/application-default.yml

###

GET http://localhost:8888/003-Base-components/application-default.properties

###

GET http://localhost:8888/003-Base-components/application-development.yml

###

GET http://localhost:8888/003-Base-components/shop-service-development.yml
