POST http://localhost:10002/payments
Accept: application/json
Content-Type: application/json

{
  "requestId": 1,
  "value": "200 PLN"
}

###

GET http://localhost:10002/payments/2f318b81-0a60-4256-bdfb-21ce7694a804
Accept: application/json
Content-Type: application/json

###

GET http://localhost:10002/payments/confirmed?pageSize=2&pageNumber=0
Accept: application/json
Content-Type: application/json

###

POST http://localhost:10000/orders
Accept: application/json
Content-Type: application/json

{
  "orderId": 1,
  "entries": [
    {
      "productId": 1,
      "quantity": 4
    }
  ]
}

###
// RestPlaceOrderUseCaseAdapter (uses RestOrderUseCaseMapper)
// PlaceOrderUseCase
// PlaceOrderService (uses PaymentsService->PaymentServiceAdapter)
// ProcessPaymentUseCase
// ProcessPaymentUseCaseAdapter (uses PaymentDomainMapper)
// ProcessPaymentService (uses PaymentIdGenerator, PaymentFeeCalculator)
// PaymentDomainWriter
// PaymentWriterAdapter (uses PaymentDomainMapper)
// PaymentWriter
// JpaPaymentRepositoryAdapter (uses JpaPaymentRepositoryMapper)
// JpaPaymentRepository

###

GET http://localhost:8888/shop-service/development/003-Base-components

###

GET http://localhost:8888/003-Base-components/application-default.yml

###

GET http://localhost:8888/003-Base-components/application-default.properties

###

GET http://localhost:8888/003-Base-components/application-development.yml

###

GET http://localhost:8888/003-Base-components/shop-service-development.yml

###

GET http://localhost:8888/008-Reactive/broker-service-development.yml

###

POST http://localhost:8080/api/shop/orders
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "orderId": 1,
  "entries": [
    {
      "productId": 1,
      "quantity": 4
    }
  ]
}

###

GET http://localhost:10001/products/1
Accept: application/json
Content-Type: application/json

###

POST http://localhost:10001/products
Accept: application/json
Content-Type: application/json

###

POST http://localhost:10003/payments
Accept: application/json
Content-Type: application/json

{
  "value": "222 PLN"
}

###

POST http://localhost:8888/monitor
Content-Type: application/x-www-form-urlencoded

path=shop-service

###

POST http://localhost:10000/actuator/refresh

###

POST http://localhost:8888/encrypt
Content-Type: text/plain

15

###

POST http://localhost:8888/decrypt
Content-Type: text/plain

795d50819d0711b36830de579828f7ab0b98b01f4a574fa2de6107a4dc264b6f

###

//@no-cookie-jar
//@no-redirect
POST http://localhost:8100/realms/shop/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

client_id=cloud&grant_type=password&username=marek&password=123

> {% client.global.set("token", response.body.access_token) %}

###

//@no-cookie-jar
//@no-redirect
POST http://localhost:8100/realms/shop/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

client_id=cloud&grant_type=refresh_token&refresh_token=eyJhbGciOiJIUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICIwMDgxNmMyZC00NzcyLTRiOGQtOTJlZi1jOTNlNDAzYTRiODcifQ.eyJleHAiOjE2NzA0OTYzNzIsImlhdCI6MTY3MDQ5NDU3MiwianRpIjoiMzEyNjc5NTQtZWNjZC00ZDQ5LTg0ZDItNDJlZThmZDUxMDVkIiwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo4MTAwL3JlYWxtcy9zaG9wIiwiYXVkIjoiaHR0cDovL2xvY2FsaG9zdDo4MTAwL3JlYWxtcy9zaG9wIiwic3ViIjoiMGMxYjllM2UtODg5Zi00N2FjLTkwMDctYmUzYWZlOTg5YTQ3IiwidHlwIjoiUmVmcmVzaCIsImF6cCI6ImNsb3VkIiwic2Vzc2lvbl9zdGF0ZSI6IjVkYjYwNjAzLTMzNmUtNDUzNS04ZTc0LWQzYmM4MzMxMDJlZiIsInNjb3BlIjoiZW1haWwgcHJvZmlsZSIsInNpZCI6IjVkYjYwNjAzLTMzNmUtNDUzNS04ZTc0LWQzYmM4MzMxMDJlZiJ9.8QuWrAUI35rUj0hAcVrNW42LgG0eea8qBpB32boOlLo

> {% client.global.set("token", response.body.access_token) %}

























