POST http://localhost:8080/api/payments
Accept: application/json
Content-Type: application/json

{
  "requestId": 1,
  "value": "200 PLN"
}

###

GET http://localhost:8080/api/payments/2f318b81-0a60-4256-bdfb-21ce7694a804
Accept: application/json
Content-Type: application/json

###

GET http://localhost:8080/api/payments/confirmed?pageSize=2&pageNumber=0
Accept: application/json
Content-Type: application/json

###

POST http://localhost:8080/api/orders
Accept: application/json
Content-Type: application/json

{
  "orderId": 1,
  "entries": [
    {
      "productId": 1,
      "price": 100,
      "quantity": 4
    }
  ]
}
