version: '3'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: "admin"
      MONGO_INITDB_ROOT_PASSWORD: "admin"
      MONGO_INITDB_ROOT_DATABASE: "payments"
  elastic-server:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.14.1
    restart: always
    container_name: elasticsearch
    environment:
      discovery.type: "single-node"
      bootstrap.memory_lock: "true"
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9300:9300"
      - "9200:9200"
  logstash-server:
    image: docker.elastic.co/logstash/logstash:7.14.1
    restart: always
    depends_on:
      - elastic-server
    container_name: logstash
    command:
      logstash -f /etc/logstash/conf.d/logstash.conf
    volumes:
      - ./configuration-files/logstash.conf:/etc/logstash/conf.d/logstash.conf
  kibana-server:
    image: docker.elastic.co/kibana/kibana:7.14.1
    restart: always
    container_name: kibana
    environment:
      ELASTICSEARCH_URL: http://elastic-server:9300
    ports:
      - "5601:5601"
