spring:
  application:
    name: warehouse-service
  cloud:
    config:
      label: 012-Docker
      fail-fast: true
      #request-connect-timeout: 10
      #request-read-timeout: 10
#eureka:
#  instance:
#    instance-id: ${spring.cloud.client.hostname}:${spring.application.name}:${spring.application.instance_id:${server.port}}
