spring:
  application:
    name: warehouse-service
  profiles:
    active: development
  config:
    import: optional:configserver:http://localhost:8888,optional:configserver:http://localhost:8889
  cloud:
    config:
      label: 007-Async-communication
      #fail-fast: true
      #request-connect-timeout: 10
      #request-read-timeout: 10
#eureka:
#  instance:
#    instance-id: ${spring.cloud.client.hostname}:${spring.application.name}:${spring.application.instance_id:${server.port}}
